apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: upload-service
    {{- include "launchpad.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: upload-service
  ports:
    - name: http
      port: {{ .Values.uploadService.port }}
      targetPort: http
